#---------------------------------#
#  Build Image                    #
#---------------------------------#
image: Visual Studio 2017

#---------------------------------#
#  Build Init                     #
#---------------------------------#
init:
  - git config --global core.autocrlf true

#---------------------------------#
#  Build Script                   #
#---------------------------------#
build_script:
  - ps: .\build.ps1 --target="AppVeyor"

#---------------------------------#
# Tests
#---------------------------------#
test: off

#---------------------------------#
#        Branches to build        #
#---------------------------------#
branches:
  # Whitelist
  only:
    - develop
    - master
    - /release/.*/
    - /hotfix/.*/
    - /feature/.*/

#---------------------------------#
#  Build Cache                    #
#---------------------------------#
cache:
- tools -> build.cake
- packages -> build.cake
